type Faculty @aws_api_key @aws_cognito_user_pools {
  facultyId:    ID!
  name:         String
  designation:  String
  deptId:       ID
  department:   String
  profileImage: String
  cvUrl:        String
  status:       String
  order:        Int
  createdAt:    AWSDateTime
  updatedAt:    AWSDateTime
}

type FacultyList @aws_api_key @aws_cognito_user_pools {
  items:     [Faculty]
  nextToken: String
}

type DesignationOptions @aws_api_key @aws_cognito_user_pools {
  items: [String]
}

input CreateFacultyInput {
  name:         String!
  designation:  String!
  deptId:       ID!
  department:   String
  profileImage: String
  cvUrl:        String
  status:       String
  order:        Int
  insertMode:   Boolean
}

input UpdateFacultyInput {
  facultyId:    ID!
  name:         String
  designation:  String
  deptId:       ID
  department:   String
  profileImage: String
  cvUrl:        String
  status:       String
  order:        Int
  insertMode:   Boolean
}

extend type Query {
  getFaculty(facultyId: ID!, tenantId: ID): Faculty @aws_api_key @aws_cognito_user_pools
  listFaculty(deptId: ID, tenantId: ID, designation: String, status: String, search: String, limit: Int, nextToken: String): FacultyList @aws_api_key @aws_cognito_user_pools
  listDesignationOptions: DesignationOptions @aws_api_key @aws_cognito_user_pools
}

extend type Mutation {
  createFaculty(input: CreateFacultyInput!): Faculty
  updateFaculty(input: UpdateFacultyInput!): Faculty
  deleteFaculty(facultyId: ID!): Faculty
}
