version = 0.1

[default.deploy.parameters]
stack_name = "myapp-dev"
resolve_s3 = true
s3_prefix = "myapp-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "ProjectName=\"myapp\" Environment=\"dev\""
image_repositories = []
confirm_changeset = true
disable_rollback = true


[default.global.parameters]
region = "ap-south-1"
[prod.deploy.parameters]
stack_name = "myapp-prod"
resolve_s3 = true
s3_prefix = "myapp-prod"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "ProjectName=\"myapp\" Environment=\"prod\""
image_repositories = []

[test-app.deploy.parameters]
stack_name = "test-app-dev"
resolve_s3 = true
s3_prefix = "test-app-dev"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "ProjectName=\"test-app\" Environment=\"dev\""
image_repositories = []
template_file = "template.test-app.yaml"
