type Department @aws_cognito_user_pools @aws_api_key {
  departmentId:  ID!
  tenantId:      ID!
  name:          String!
  shortName:     String!
  hod:           String
  established:   Int
  totalFaculty:  Int
  totalStudents: Int
  status:        String
  description:   String
  imageUrl:      String
  createdAt:     AWSDateTime
  updatedAt:     AWSDateTime
}

type DepartmentList @aws_cognito_user_pools @aws_api_key {
  items:     [Department]
  nextToken: String
}

input CreateDepartmentInput {
  name:        String!
  shortName:   String!
  hod:         String
  established: Int
  description: String
  imageUrl:    String
  status:      String
}

input UpdateDepartmentInput {
  departmentId:  ID!
  name:          String
  shortName:     String
  hod:           String
  established:   Int
  totalFaculty:  Int
  totalStudents: Int
  description:   String
  imageUrl:      String
  status:        String
}

extend type Query {
  getDepartment(departmentId: ID!): Department @aws_cognito_user_pools @aws_api_key
  listDepartments(limit: Int, nextToken: String): DepartmentList @aws_cognito_user_pools @aws_api_key
}

extend type Mutation {
  createDepartment(input: CreateDepartmentInput!): Department
  updateDepartment(input: UpdateDepartmentInput!): Department
  deleteDepartment(departmentId: ID!): Department
}
