type News {
  news_id: ID!
  constituency: String
  ward: String
  dateTime: AWSDateTime
  information: String
  incidentType: String
  imageUrl: String
  createdBy: String
  created_at: AWSDateTime
  updated_at: AWSDateTime
}

type NewsConnection {
  items: [News!]!
  nextCursor: String
}

input CreateNewsInput {
  news_id: ID
  constituency: String!
  ward: String!
  dateTime: AWSDateTime!
  information: String!
  incidentType: String!
  imageUrl: String
}

input UpdateNewsInput {
  constituency: String
  ward: String
  dateTime: AWSDateTime
  information: String
  incidentType: String
  imageUrl: String
}

extend type Query {
  getNews(news_id: ID!): News
  listNews(
    constituency: String
    ward: String
    incidentType: String
    pagination: PaginationInput
  ): NewsConnection
}

extend type Mutation {
  createNews(input: CreateNewsInput!): News
  updateNews(news_id: ID!, input: UpdateNewsInput!): News
  deleteNews(news_id: ID!): Boolean
}
